[package]
name = "facekey"
version = "4.0.0"
edition = "2021"
description = "FaceKey - Face ID for Linux. Qt front-end and setup wizard for Howdy face authentication"
authors = ["Ali120B"]

[dependencies]
cxx = "1.0"
cxx-qt = "0.8.1"
cxx-qt-lib = { version = "0.8.1", features = ["qt_full"] }
libloading = "0.8"

[build-dependencies]
cxx-qt-build = "0.8.1"

[[bin]]
name = "facekey"
path = "src/main.rs"
